### ISSUE TITLE
Latest version Crashes at very high rate

### ISSUE THREAD

**Issue by rafale77** [Hackworth/VeraHomeKitBridge#10]
Most likely related to the changes in HAP nodeJS. Can barely keep the bridge up as it crashes every few minutes. Reverted back to a previous version and is stable.

**Comment by hackworth** [comment]
I'm surprised to hear this, it's been rock-solid for me and I didn't have a single failure adding quite a few devices. Do you have an error message you can post?

**Comment by rafale77** [comment]
events.js:85                                                                                                                                                                                                                                                                                                                      throw er; // Unhandled 'error' event                                                                                                                                                                                                                                                                                              ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at new EventedHTTPServerConnection (/home/xxx/Public/VHKB/lib/HAP-NodeJS/lib/util/eventedhttp.js:125:20)
    at EventedHTTPServer._onConnection (/home/xxx/Public/VHKB/lib/HAP-NodeJS/lib/util/eventedhttp.js:79:20)
    at Server.emit (events.js:107:17)
    at TCP.onconnection (net.js:1330:8)

npm ERR! Linux 3.16.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! VeraHomeKitBridge@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the VeraHomeKitBridge@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the VeraHomeKitBridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls VeraHomeKitBridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/Public/VHKB/npm-debug.log

I have no memory of ever seeing this error on the previous version of the HAP-nodeJS.

**Comment by rafale77** [comment]
I have tried upgrading nodeJS to 5.1.1 and am still observing crashes within a minute of launch. I tried using only one iOS device. not sure what is going on here.
The latest versions has less of a problem adding devices. I have noticed much rarer communication errors but I can't seem to keep it up.

**Comment by hackworth** [comment]
It's basically saying a port is in use, which is odd because one of my earlier commits specifically added a node module to fix this. Can you open app.js, find the line which lists the port 51826 and lower the number, see if that solves your issue? Try, perhaps, 40000?

**Comment by rafale77** [comment]
I will but I doubt it is the problem. The previous version I have also calls out   portfinder.basePort = 51826 and does not crash at all. I am running quite a few things on my linux box (echo hue bridge, airsonos, sonos http api) which don't seem to be using this port...

**Comment by hackworth** [comment]
That's why I'm confused. None of this should have changed. Regardless, I just pushed a change so it looks at 127.0.0.1 for open ports, rather than 0.0.0.0, can you `git pull` and try again? 

51826 is just the starting port, it will increment from there. Each of your devices/scenes will use a port.

**Comment by rafale77** [comment]
Yes I realize that but my number of devices is the same in both cases. I am not finding anything in your code changes which should trigger this except for changes in the HAP-NodeJS which are a bit obscure to me. I will pull and test again. It is just a but time consuming to re-add the 26+ devices I want to control with siri so I will get around to do it at some point later this week.

**Comment by hackworth** [comment]
Actually, you raise a good point. Adding a ton of devices suck, and converting this to a proper bridge rather that one device = one server should resolve your port issue, so that's exactly what I did. 39b422f4b891dac13779af334a99454d63c0f76e

**Comment by rafale77** [comment]
Brilliant! Seems to work but I have so many scenes and devices it is a bit overwhelming at first. ;-). Now I have to sort them by room and zones etc...

**Comment by hackworth** [comment]
Awesome! Glad it seems to work, I'll go ahead and close two issues out for now, let me know if they pop back up.
