### ISSUE TITLE
Bridge stops working after a few minutes

### ISSUE THREAD

**Issue by holgicgn** [Hackworth/VeraHomeKitBridge#13]
First of all: Hackworth great job! Thanks.

But I also have one problem.
I've installed Vera HomeKitBridge on my Raspberry Pi (newest Debian Jessie OS) as described on your readme file. I've edited config.json (Veras IP Adress / Garage door names not changed). Everything works fine with EVE and MyTouchHome. I can see most of my 22 Vera Devices...
After a few minutes the iOS apps are no longer connectet with Vera HomeKitBridge. It seems that the bridge will not work anymore.
After deleting the HomeKit on my IPhone and start searching the Device (Bridge) in EVE or MyTouchHome nothing is found.
I've tried to  "nam run start" but it seems that Bridge is still running.
I've rebooted my Raspberry, started again HomeKitBrige and its working again - but only for 5 minutes, then the same problem occurs.  :'(

Any Ideas?
(If you need a log file, pleas let me know how to create it - unfortunately I'm a beginner ;)

**Comment by rafale77** [comment]
I don't mean to offend but... 
1. When you start the bridge, how do you do it? What OS are you using? 
If you are using a remote console like SSH through putty or terminal, you close the bridge as soon as you close the window.
2. When you lose connection to the bridge, it should mean that the bridge crashed and you should see an error list displayed on the session. If you have closed it... which I am suspecting is what happened, you already killed the bridge.
3. You normally should not have to remove anything from EVE or mytouchhome. Restarting the bridge should recover all your devices. When the bridge crashes, the devices should only be grayed out.

**Comment by holgicgn** [comment]
Thanks for your quick reply :+1: 
1. 
   I work directly on the raspberiy (latest jessie version) via monitor/keybord 
   (I've also tried via Terminal from my Macbook, but if, the window was allways open).
   I change to VeraHomeKitBride directory and start with "npm run start". A list of all devices is shown, and at the first time also all switch commands from EVE (from my iOS 9.2 iPhone).
   After x minutes every device (and also the Bride) is shown as "not available" and actually "last seen 10 minutes ago" (translated from german) in EVE. In mytouchhome everything is grayed out. Also Siri says that she can't do it (switching on the light for example).

2.
I see no error list on the screen, it shows the last switching command and nothing else.

Crazy: while I wrote this, I saw on the Pi Monitor that the Bridge starts reading the status of some of my devices, and now I can see and control everything again on EVE. 
And now, 4 minutes later the same problem: not available on EVE

When starting Bridge the following Message is shown:

> VeraHomeKitBridge@1.0.0 start /home/pi/VeraHomeKitBridge
> node app.js

**\* WARNING **\* The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs
**\* WARNING **\* The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister
Starting Vera HomeKit Bridge...
Create accessory: Bogenlampe Wohnz.
Create accessory: Brunnen Balkon
Create accessory: Licht Balkon Kueche
Create accessory: Licht Balkon WZ
Create accessory: Licht Bild Flur
Create accessory: Licht Wohnzimmer
Create accessory: Multimedia Bass
Create accessory: Multimedia TV Rack
Create accessory: Rollo Buero
Create accessory: Rollo Kueche
Create accessory: Rollo Schlafzimmer Links
Create accessory: Rollo Schlafzimmer Rechts
Create accessory: Rollo Wohnzimmer Links
Create accessory: Rollo Wohnzimmer Rechts
Create accessory: Schreibtisch
Create accessory: TV Schlafzimmer
Create accessory: Aufstehen
Create accessory: Auto-Beleuchtung
Create accessory: Beleuchtung Aus
Create accessory: Beleuchtung an
Create accessory: Display Galaxy aktivieren
Create accessory: Fernsehen Schlafzimmer
Create accessory: Gehen
Create accessory: Kommen
Create accessory: Rolladen Fernsehen
Create accessory: Rolladen Stop
Create accessory: Rolladen hoch alle
Create accessory: Rolladen hoch vorne
Create accessory: Rolladen runter
Create accessory: Rolläden Sonnenschutz Werktag
Create accessory: Rolläden Sonnenschutz hoch
Create accessory: Schlafen

**Comment by holgicgn** [comment]
Damn... I've got it.
It was a WIFI problem. It seems that the system is very sensitive in case of a bad or shortly interrupted wifi connection...  I've connected the Raspbery via lan cable and now it works fine for more than 1 hour :)
But thanks for your support rafale :+1:
