### ISSUE TITLE
Can't start Server

### ISSUE THREAD

**Issue by CelticWebSolutions** [Hackworth/VeraHomeKitBridge#17]
VeraHomeKitBridge@1.0.0 start /usr/local/lib/node_modules/VeraHomeKitBridge

> node app.js

Starting Vera HomeKit Bridge...
Create accessory: Appliance Module 1
Create accessory: Attic Relay old
Create accessory: Back door light
Create accessory: Conservatory light
Create accessory: Double Garage
Create accessory: Front Doorway Light
Create accessory: Garage Outer Lights
Create accessory: Garage Unused Relay
Create accessory: Gates
Create accessory: Hallway Light
Create accessory: Kitchen Unit lights
Create accessory: Landing light
Create accessory: Master Bedroom Light
Create accessory: Plug1-Computers
Create accessory: Qubino Relay
Create accessory: Single Garage Door
Create accessory: TV Socket
Create accessory: Unused in Attic
Create accessory: Turn off front door light 10PM
Create accessory: Turn on Front door light at Dusk
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/VeraHomeKitBridge/lib/HAP-NodeJS/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/VeraHomeKitBridge/lib/HAP-NodeJS/lib/HAPServer.js:138:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/VeraHomeKitBridge/lib/HAP-NodeJS/lib/Accessory.js:347:16)
    at /usr/local/lib/node_modules/VeraHomeKitBridge/app.js:38:24
    at Server.onListen (/usr/local/lib/node_modules/VeraHomeKitBridge/node_modules/portfinder/lib/portfinder.js:49:5)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! VeraHomeKitBridge@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the VeraHomeKitBridge@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the VeraHomeKitBridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs VeraHomeKitBridge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls VeraHomeKitBridge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/VeraHomeKitBridge/npm-debug.log

[npm-debug.txt](https://github.com/Hackworth/VeraHomeKitBridge/files/306715/npm-debug.txt)

**Comment by larryebaum** [comment]
@CelticWebSolutions Not sure if you've solved this but it seems that you may have another instance of homebridge running, hence the error `Error: listen EADDRINUSE :::51826` telling you that the homebridge port 51826 is in use. I'd had that occur when I was also executed homebridge directly. Check running processes for homebridge and kill off any and try running again.

**Comment by CelticWebSolutions** [comment]
Yes, all sorted now thank you.
