### ISSUE TITLE
Bridge is up but no longer able to add to homekit

### ISSUE THREAD

**Issue by rafale77** [Hackworth/VeraHomeKitBridge#21]
Strange thing occurring. Was still working till yesterday afternoon but in the evening found that all the devices from my bridge disappeared. Decided to update ubuntu and the bridge with the garage door update. The bridge comes back up with no error on nodejs 4.4.7.
I am able to get Homekit to see the bridge but when I try adding it, HomeKit says it can't be reached... "Adding Failed, Could not connect to accessory". Been trying older nodejs and the development version with the same result. Not sure if it is because I suddenly have too many devices on the vera or if I have some unrecognized device types homekit does not like...

**Comment by bytedreamer** [comment]
Double check that the IP Address in config.json is correct. It may have been reverted to the default.

**Comment by rafale77** [comment]
Thanks but no, The bridge is working fine, it finished discovery and is running. Homekit just won't connect to it . I am completely convinced now that it is due to the number of devices I have on the Vera which exceeds what homekit is willing to handle. I have tested the homebridge version on which I can exclude all the sensors from being published and that one runs fine. May need to add an option on the bridge to selectively ignore devices. I think I am already over 200 devices on my vera. The only thing that changed between when it was working and when it stopped was me including two more devices to my system. Two switches...

**Comment by bytedreamer** [comment]
Wow, that is a large home automation system. I hope that Apple allows for additional devices in iOS 10.

**Comment by rafale77** [comment]
I think it is a limitation per bridge I must have broken. Some of the devices are apps or are child devices of other devices. Either have to break it down into several bridges or have to limit what is being broadcasted through the bridge. Security sensors have little value for Homekit for example. Would be nice to take them out.

**Comment by wooconstructions** [comment]
Hi Rafale, have you workout how to exclude sensors and selected screen on VeraHomeKitBridge? I have about 70 devices and it does drop out every now and then; and like you said, sensors and some screen are not needed to be included in the bridge. Sorry for this late comment.

**Comment by rafale77** [comment]
Unfortunately no. I have given up a bit on the bridge and Homekit in general given that I have found workarounds with Amazon's Alexa and it appears superior to Siri anyway.

**Comment by wooconstructions** [comment]
Haha, I am using Alexa as well (In Canberra Australia).  I still like to make VeraKitHomeBridge work because I got it working with AppleTV4 using siri to control my veralite remotely (for a week), then it stop working remotely and only work at home. And sometime it drop out.  I thought it could be something to do with the device limit.  Anyway, thanks for the quick reply. Jacky

**Comment by ibrewster** [comment]
Well, I, for one, am _not_ using Alexa, and would love to see this feature. I have dozens of scenes that are designed to run in response to other actions and will never be triggered directly, and it would be nice to get them out of the list that shows up in home kit. So if someone (obviously not Rafale, since he has changed platforms) could implement such a thing, I, for one, would be quite happy.

**Comment by bitmerchandise** [comment]
Check out homebridge-Vera then from damianxd. He has ignore devices and scenes are seen as devices so you can ignore all those scenes or devices that you don't want in HomeKit. Only thing that I don't like is that to open garage door you a have to say turn on garage.  With verhomekitbridge you can say open garage

**Comment by Phigital-Inc** [comment]
There is a way to modify the app.js to allow only desired scenes. See this post here:
http://forum.micasaverde.com/index.php/topic,31716.msg283812.html#msg283812

I have VeraHomeKitBridge running and stable, but for some reason only with Node 4.5.0 installed via the package installer works.

**Comment by rafale77** [comment]
Closing since it is an an issue with the bridge but a limitation with Homekit. It's almost a year old and have since edited my version to ignore scenes and select devices.
