### ISSUE TITLE
Siri Commands Stopped Working

### ISSUE THREAD

**Issue by larryebaum** [Hackworth/VeraHomeKitBridge#22]
Unsure where this would fit, but figured someone could at least verify results on their end...

I used to be able to issue verbal command 'turn off all lamps' and VHKB would comply. I recent troubleshooting stint had me npm update all (delete persist) and re-add accessory. End result, this command no longer works (useful at bedtime).

Curious if it works for others, and if so, can then try to figure out what changed, versions, etc.

Unrelated, anyone got this working at startup? I've had zero luck setting as global daemon on OSX.  I've tried various ways including launchd without success....

**Comment by hackworth** [comment]
Have you gone into your preferred HomeKit application and changed your lights to be lights? HomeKit adds things as switches, you have to manually convert them to lights. I've tested and yes, it works fine for me.
