### ISSUE TITLE
Randomly fail when adding devices

### ISSUE THREAD

**Issue by rafale77** [Hackworth/VeraHomeKitBridge#6]
Having a lot of devices on the Vera, HomeKit sometimes fail to add devices. Then the device is blacklisted and HomeKit will refuse to try to add it again even if the bridge is reset (Restarted after the persist folder is deleted). Not sure why adding the device sometimes fails. Using node.js 0.12.7
Also newer node.js versions prevent starting the program unless modified.

**Comment by rafale77** [comment]
Digging further into it, it seems to be related to how active/busy homekit is when devices are being added. If during the add process another device is pinging homekit, failure rate is much greater. I would get "HMErrorDomain 4" if I try to ad it again. The device is added to the persist folder but not to homekit. deleting the device from the persist folder does not help.

**Comment by hackworth** [comment]
Resolved in #10
